[project]
name = "agent-py-demo-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.37.22",
    "botocore>=1.37.22",
    "logging>=0.4.9.6",
]
